### ISSUE TITLE
Version 1.0.6 added every hooks in the report

### ISSUE THREAD

**Issue by mohamadsyauqi** [extent-framework/extentreports-cucumber4-adapter#10]
Hello, I notice in the 1.0.6, the report has additional step for every cucumber hooks e.g. before, after, afterstep. 

![106](https://user-images.githubusercontent.com/46016468/50944555-e25a5c00-14cb-11e9-91c6-3fc84504a17d.PNG)

I think now the report has a lot of unnecessary information. I just want to see only the steps in the feature files. Is this intended or bug?

**Comment by foursyth** [comment]
Please use `1.0.5` for now.  This was supposed to be only for errors only but the hook is injected before/after each step.
