### ISSUE TITLE
Screenshot not embedded LoggerReport and not present in ExtentHtml

### ISSUE THREAD

**Issue by chetand24** [extent-framework/extentreports-cucumber4-adapter#13]
I ran simple test and expecting the screenshot embedded to the ExtentHtml report but its not present. 

I can see "img" icon/link in the LoggerReport but it does not show the image embedded.

When I inspect the element I found following:
<a href="#" class="indigo badge" data-featherlight="<absolute path>/test-output/embedded1.png">img</a>

I can see the "embedded1.png" image present in the location.

here is my script for the screen attach.

if(scenario.isFailed()){
            try {
                byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
                scenario.embed(screenshot, "image/png");
            } catch (WebDriverException wde) {
                System.err.println(wde.getMessage());
            } catch (ClassCastException cce) {
                cce.printStackTrace();
            }
}

I am using following version:
compile "com.aventstack:extentreports-cucumber4-adapter:1.0.6"
AND testCompile group: "io.cucumber", name: "cucumber-java8", version: "4.2.3"

FYI: I am using this for mobile (ios) automation, using appium.

**Comment by ranamanas** [comment]
@anshooarora Could you please look into this , i could see the same issue from my end.

**Comment by anshooarora** [comment]
Marking this as a bug but would not recommend using LoggerReporter for BDD. SparkReporter works a lot better for this.

**Comment by anshooarora** [comment]
Please use `ExtentSparkReporter`, it is the default reporter and starting the latest release `4.10.0`, it is a SPA style view just like the V3HtmlReporter.
