### ISSUE TITLE
How to add log within step definition, please provide an example 

### ISSUE THREAD

**Issue by mgmankush** [extent-framework/extentreports-cucumber4-adapter#14]
@anshooarora I need a example where how text log like text , json can be added within certain step definition.

**Comment by mohamadsyauqi** [comment]
@mgmankush use scenario.write() but it only supported in the newest version which is 1.0.6.
Example:
```
@Before
public void beforeStep(Scenario scenario) {
	this.scenario = scenario;
}

@Given("write scenario")
public void open_event_viewer() {
	scenario.write("text here");
}
```

**Comment by mgmankush** [comment]
@mohamadsyauqi thanks for the help :) , still it didn't solve my purpose. 
I want to add these logs/text under the step definition within  html report ex i want to capture input data or api response

**Comment by mohamadsyauqi** [comment]
@mgmankush am I misunderstood you or what? I think you have the exact issue as mine #7 where you want to put a log or text under every steps in html report. If so, the first example I gave you is the way to do it.

**Comment by mgmankush** [comment]
@mohamadsyauqi It does add a log under console but not in html report :( I even tried scenario.embed , still its not adding under html report

**Comment by mohamadsyauqi** [comment]
@mgmankush What version you are using? Is it the new one? If so then maybe there's a bug in the new version that affected that see #10 . Currently, I'm using my own jar where I did update the scenario.write() and using the old version to work. If you want I can share it with you. The problem is you need download it and add the dependency with the path to the jar, I can share that with you that too if you want. Can't really do anything else except wait for the dev to fix and upload to maven repo (I dont really know the process of uploading to maven repo).

**Comment by mgmankush** [comment]
@mohamadsyauqi I am using the latest version 1.0.6 of it. If possible can u share the jar with me .really thanks for the help :)

**Comment by mohamadsyauqi** [comment]
@mgmankush Download it from [here](https://github.com/mohamadsyauqi/extent-jar).
Create a new folder named lib at the root folder of the project.
Copy the new jar file into the lib folder.
Add the following dependency in the pom.xml file :
```
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports-cucumber4-adapter</artifactId>
    <version>1.0.5</version>
    <scope>system</scope>
    <systemPath>${basedir}/lib/extentreports-cucumber4-adapter-1.0.5.jar</systemPath>
</dependency>
<dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>4.0.5</version>
</dependency>
```
This is the maven dependency, if you are using gradle or something else try to search on how to convert it cause I dont know. Btw, this is the current way I'm doing it, I dont know if there's more efficient way to do this. Hope this help you.

**Comment by anshooarora** [comment]
Hmm, as far as I know, `scenario.write(text)` would output the information at the Step/Scenario level to the HTML report. Is that not happening for you?

**Comment by ashwinipotadar** [comment]
@anshooarora Thank you for the excellent reporting plugin. 

I followed https://github.com/extent-framework/extentreports-cucumber4-adapter and able to generate HTML report using extentreports-cucumber4-adapter

I want to know how to add 
1. Logs in this format test.log(Status.INFO, "Starting test for scenario " );
2. Embed screenshots in the report

Below are some details

I am working on Selenium Cucumber project. I am using the below versions:

Cucumber-core 4.2.0
Cucumber-java 4.2.0
Cucumber-junit 4.2.0
extentreports-cucumber4-adapter 1.0.7
I am able to generate an HTML report. However, I want to know how to add screenshot and logs using the extentreports-cucumber4-adapter

RunCukes.java file as below

import org.junit.experimental.categories.Category;
import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

@RunWith(Cucumber.class)
@CucumberOptions(features = <PATH>,
glue = {"testcases.periscope"},plugin = {"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:", "json:target/cucumber-report.json","html:target/Report.html"})
//@Category(Example.class)
public class RunCukesTest {
}

**Comment by anshooarora** [comment]
@ashwinipotadar 

You can use either or:

```
@After
public void after(Scenario scenario) {
    scenario.embed(extractBytes("img.png"), "image/png");
}

@AfterStep
public void afterStep(Scenario scenario) {
    scenario.embed(extractBytes("img.png"), "image/png");
}
```

**Comment by kkrkirankumar** [comment]
if you are using extent reports. "Reporter.addsteplog()" can help.
