### ISSUE TITLE
Check for license requirements

### ISSUE THREAD

**Issue by sivaram-vu** [extent-framework/extentreports-cucumber4-adapter#15]
I check that this repository is MIT licensed so I understand that this is free to customize and use for my specific requirements as long as I include the MIT license file.  Kindly please confirm.

Bit more info,
I do not want to use customization's of the BDD reporter.  Just want to use with HTML reporter to have the basic reports.

**Comment by anshooarora** [comment]
Yes, you can make any customization necessary, there are no such restrictions.

PS.  You do know that it is possible to use any reporter via System settings or [properties configuration](https://github.com/extent-framework/extentreports-cucumber4-adapter/blob/master/src/test/resources/com/aventstack/adapter/extent.properties), right?

**Comment by sivaram-vu** [comment]
Thank you Anshooarora. 
So, I understand now.. This can be used with any reporter and the reporters which are tagged as pro are licensed.

**Comment by anshooarora** [comment]
Applies to all reporters.

**Comment by anshooarora** [comment]
Applies to all reporters.
