### ISSUE TITLE
Report is not being generated when using testNg

### ISSUE THREAD

**Issue by x0156** [extent-framework/extentreports-cucumber4-adapter#16]
Extend Report is not being generated when using testNg as test runner. But works fine with junit though.
Tested with the [Sample Project](https://github.com/foursyth/extentreports-cucumberN-example)

Env: Java1.8 + maven
Adapter: 1.0.6
testng: 6.11
cucumber : 4.2.4

**Comment by anshooarora** [comment]
I have tested and am able to generate a report.  Can you please create a small project so I can test?

**Comment by kathyrollo** [comment]
```
public class RunCukesTest extends AbstractTestNGCucumberTests{ }
```
Been using the above for the longest time and reports have generated just fine.

Confirmed working combinations are:

TestNG
```
<dependency>
	<groupId>io.cucumber</groupId>
	<artifactId>cucumber-testng</artifactId>
	<version>4.2.0</version>
</dependency>

<dependency>
	<groupId>com.aventstack</groupId>
	<artifactId>extentreports-cucumber4-adapter</artifactId>
	<version>1.0.5</version>
</dependency>
```

JUnit
```
<dependency>
	<groupId>io.cucumber</groupId>
	<artifactId>cucumber-junit</artifactId>
	<version>4.2.0</version>
</dependency>

<dependency>
	<groupId>com.aventstack</groupId>
	<artifactId>extentreports-cucumber4-adapter</artifactId>
	<version>1.0.5</version>
</dependency>
```

Best to wait for the `1.0.11` release in #20.

**Comment by anshooarora** [comment]
@x0156 I tested again and this works.  Please share the code snippet that helps me reproduce the behavior you are seeing.

**Comment by x0156** [comment]
@anshooarora  sorry didn't see your earlier  comment. i neither could find the project with issue nor reproduce now.so closing this now. thanks!
