### ISSUE TITLE
Location for saving screenshots should be customizable

### ISSUE THREAD

**Issue by deena-p** [extent-framework/extentreports-cucumber4-adapter#2]
This extent-report is not portable with screenshot attached as currently it is hard coded as test-output. Is that possible to our provide own server location to store screenshots? Similarly will it be a good idea to provide our own file name too?

In case if we need to access to a window shared location from Mac, will it work?

**Comment by anshooarora** [comment]
I would propose configuring the location from the existing `extent.properties` as such:

```
screenshot.dir=/usr/tests/screenshots/
```

or from System:

```
System.setProperty("screenshot.dir", "/usr/tests/screenshots/");
```

or direct (will also set this as a system property):

```
ExtentService.setProperty("screenshot.dir", "/usr/tests/screenshots/");
```

A note for System or ExtentService - you must ensure this setting is created before any of the tests start.

**Comment by anshooarora** [comment]
Please check with `1.0.5-SNAPSHOT`.  

 * Setup `screenshot.dir` from [extent.properties](https://github.com/extent-framework/extentreports-cucumber4-adapter/blob/master/src/test/resources/com/aventstack/adapter/extent.properties)
 * Use `System.setProperty("screenshot.dir", "path")` before any of your tests start

**Comment by deena-p** [comment]
Test OK for different inputs except below one.

For the below path
screenshotPath = "\\\\Server\\Data\\Automation\\Screenshot\\" + executionEnvironment.toLowerCase() + "\\" + browserType.toLowerCase() + "\\" + "dummy\\"
it is skipping the last folder dummy and storing the screenshots in 
"\\\\Server\\Data\\Automation\\Screenshot\\" + executionEnvironment.toLowerCase() + "\\" + browserType.toLowerCase() + "\\"

**Comment by foursyth** [comment]
No luck reproducing this..  btw, I am using unix style separator `/`. Try:

```
//Server/Data/Automation/Screenshot\" + executionEnvironment.toLowerCase() + "/" + browserType.toLowerCase() + "/dummy/"
```

**Comment by deena-p** [comment]
Hi @foursyth I am using windows machine and having windows server shared folders for storing screenshots.
Here is the code that creating the issue (Not sure why it is behaving like that) in the extentreports-cucumber4-adapter-1.0.4 adapter:

In ExtentCucumberAdapter.class
line no: 201
return new URL((new File(screenshotDir)).toURI().toURL(), fileName);

For the input of "\\\Server\Data\Automation\Screenshot\chrome\30-11-2018\fyZfp\dummy (or any value)\"
it is returning "file:////Server/Data/Automation/Screenshot/chrome/30-11-2018/fyZfp/embedded1.png"

**Comment by foursyth** [comment]
Hmm,  for this feature I suggest sticking to 1.0.5-SNAPSHOT for now.  If it works, I will give @anshooarora a nudge to release to central.

**Comment by deena-p** [comment]
Thanks. I think it shouldn't stop to release.

**Comment by foursyth** [comment]
@anshooarora please see @deena-p note above, this can be released to central

**Comment by anshooarora** [comment]
1.0.5 released to central

**Comment by deena-p** [comment]
> > 1.0.5 released to central
> 
> I did not see it yet.

Got it

**Comment by sandeepmknair** [comment]
Hi Anshoo,

Thanks for your great work..!!
I want to place the exntent.properties under src/main/resource/anyfolder ..It works only in under resource folder.It doesnt pick if I create a an additional folder.Could you please help me here.

**Comment by vzenzo** [comment]
> Hi Anshoo,
> 
> Thanks for your great work..!!
> I want to place the exntent.properties under src/main/resource/anyfolder ..It works only in under resource folder.It doesnt pick if I create a an additional folder.Could you please help me here.

This would be soooooo helpful as all of my config files are under resources/properties/configurations/

The only propertie file  sticking out is extent.properties

Also just to return to topic, none of these solutions work, I have all the latest version, tried clean install -U, tried every solution none of them work. 

The screenshot keeps being saved in test-output and it won't change no matter what I do.

**Comment by anshooarora** [comment]
@vzenzo Please use the latest release `1.0.11` and refer to [this section](https://github.com/extent-framework/extentreports-cucumber4-adapter#attaching-screenshots).
