### ISSUE TITLE
Time taken in the report is displayed as Zero

### ISSUE THREAD

**Issue by dustin2020** [extent-framework/extentreports-cucumber4-adapter#21]
Cucumber3-Adapter and Cucumber4-Adapter is not computing the Time taken in the report and every time this is generated it displays zero.

@RunWith(Cucumber.class)
@CucumberOptions(features = "src/test/resources/features", 
                 glue = { "com.extentReport.ExtentReport.stepdef" },
                		 tags = {"@healthcheck"},
		         plugin = {"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:", "json:target/cucumber-report.json"})
public class RunCukesTest {
}

extent.properties
============
extent.reporter.avent.start=true
extent.reporter.bdd.start=true
extent.reporter.cards.start=true
extent.reporter.email.start=false
extent.reporter.html.start=true
extent.reporter.klov.start=false
extent.reporter.logger.start=true
extent.reporter.tabular.start=true

extent.reporter.avent.config=
extent.reporter.bdd.config=
extent.reporter.cards.config=
extent.reporter.email.config=
extent.reporter.html.config=
extent.reporter.klov.config=
extent.reporter.logger.config=
extent.reporter.tabular.config=

extent.reporter.avent.out=test-output/AventReport/
extent.reporter.bdd.out=test-output/BddReport/
extent.reporter.cards.out=test-output/CardsReport/
extent.reporter.email.out=test-output/EmailReport/ExtentEmail.html
extent.reporter.html.out=test-output/HtmlReport/ExtentHtml.html
extent.reporter.logger.out=test-output/LoggerReport/
extent.reporter.tabular.out=test-output/TabularReport/

@anshooarora

**Comment by anshooarora** [comment]
@dustin2020 Looking into this and a bunch of other issues affecting the core-API and lower adapter versions.  Please bare with me, I will have an update soon.

**Comment by anshooarora** [comment]
Unable to reproduce this, can you please check with version `1.0.9`?
