### ISSUE TITLE
Parameters are empty in the scenario outline in the reports

### ISSUE THREAD

**Issue by dineshven** [extent-framework/extentreports-cucumber4-adapter#27]
Scenario Outline: Verify the "**<DateTimeFormat>**"  Format section in the settings screen
    Given I tap the Date Time section in android settings
    When I select the following "<DateTimeFormat>"
   Examples:
      | DateTimeFormat |

Extent report does not display the parameter for the Scenario Outline. I have highlighted them in bold.

**Comment by kathyrollo** [comment]
Make sure you are formatting your gherkin correctly.
```
  @TC31
  Scenario Outline: Sort by_Price and Product Name
    When I Search Product: '<query>'
    When I Sort By: '<option>'
    Then I Should See Products Sorted By: '<option>'

    Examples:
      | query   | option               |
      | asti    | Price (Low to high)  |
      | italian | Product Name (Z - A) |
```

![scenario_outline_params](https://user-images.githubusercontent.com/28589393/73700579-01610700-473b-11ea-8d5d-b57b1f7058b1.PNG)

**Comment by anshooarora** [comment]
Thank you @kathyrollo

**Comment by cent-kebinjoy** [comment]
It doesn't work in the scenario outline title

 `  @TC31
  Scenario Outline: Sort by '<option>'
    When I Search Product: '<query>'
    When I Sort By: '<option>'
    Then I Should See Products Sorted By: '<option>'

    Examples:
      | query   | option               |
      | asti    | Price (Low to high)  |
      | italian | Product Name (Z - A) |
`
![image](https://user-images.githubusercontent.com/87461874/126098501-153d36f9-67f6-479c-be8a-05f3c573b8c0.png)
