### ISSUE TITLE
Unable to see Screenshot in the Extent Cucumber Logger Report.

### ISSUE THREAD

**Issue by vishalmgada** [extent-framework/extentreports-cucumber4-adapter#28]
I am unable to see screenshot getting captured in the Extent report for cucumber. I am using the below code: 

`public void screenshot(Scenario scenario) {
		   	if(scenario.isFailed()) {
	    		  byte[] screenshot=SeleniumUtils.captureScreenshot();
	 		   scenario.public void screenshot(Scenario scenario) {
	embed(screenshot, "image1/png");
	 	   }`

**Runner File**

`@RunWith(Cucumber.class)
@CucumberOptions(
    features = "src/test/java/features", tags = "@login_internal_user", glue = {
        "stepDefinitions"
    }, plugin = {
        "pretty",
        "rerun:src/test/java/features/rerun.txt",
        "com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:",
       }
)
public class loginRunner {
}
`
**Extent Properties File**

`# indicate which reporters to use

extent.reporter.logger.start=true
# point to any configuration used
extent.reporter.logger.config=src/main/resources/extent-config.xml

# specify output path
extent.reporter.logger.out=reports/importsTeam-reports
screenshot.dir=reports/importsTeam-reports/screenshots/`

**Maven Properties**
Extent Cucumber Adapter version- 1.0.7
Cucumber Jars- 4.2.0

**Comment by vishalmgada** [comment]
@anshooarora Can you please help us here?

**Comment by Lufis** [comment]
Same problem!!

**Comment by anshooarora** [comment]
All - I will look into this, but would also encourage you to not use the Logger formatter as it will be deprecated in the next major release.

**Comment by anshooarora** [comment]
All - please upgrade to the latest release and use `ExtentSparkReporter` or `extent.reporter.spark.start=true`.  V3HtmlReporter and LoggerReporter will be deprecated as I would like to focus on a single reporter moving forward.  The SparkReporter starting the latest release creates a single report view just like V3HtmlReporter and is better suited for BDD style reports.
