### ISSUE TITLE
Not able to see the attached screenshot in the report

### ISSUE THREAD

**Issue by elaya2410** [extent-framework/extentreports-cucumber4-adapter#29]
I have attached screenshot in the report whenever the scenario is failed.
But I am not able to see the screenshot in the report.
Kindly help me out.

**Comment by Lufis** [comment]
Same problem here... Did you get the solution? Best regards...

**Comment by elaya2410** [comment]
I have added method for adding screenshot and raised pull request.
But it is still open. If it is approved you can use the code for attaching screenshot

**Comment by anshooarora** [comment]
@elaya2410 - thank you for the PR.  I wanted to ask how is exposing the 3 methods different from using hooks?
