### ISSUE TITLE
Update documentation for screenshot usage

### ISSUE THREAD

**Issue by foursyth** [extent-framework/extentreports-cucumber4-adapter#3]
## Summary

The documentation for this adapter needs update with all the features available, but the screenshot functionality in particular.  

The below 2 comments can be used:

* [how-to:capture](https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/1#issuecomment-441095327)
* [how-to:adapter](https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/2#issuecomment-441774335)

**Comment by anshooarora** [comment]
Updated [readme.md](https://github.com/extent-framework/extentreports-cucumber4-adapter#attaching-screenshots).
