### ISSUE TITLE
Extent Report nor getting generated in Cucumber

### ISSUE THREAD

**Issue by HegdeMangala** [extent-framework/extentreports-cucumber4-adapter#32]
Hi I am new to selenium cucumber and trying to generate extent report.I am using latest versions of cucumber and my java version is 13.Could anyone please help me.I have attached pom 

    `<project xmlns="http://maven.apache.org/POM/4.0.0" 
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven- 
    4.0.0.xsd">
     <modelVersion>4.0.0</modelVersion>

      <groupId>ABC</groupId>
     <artifactId>ABC</artifactId>
     <version>0.0.1-SNAPSHOT</version>
     <packaging>jar</packaging>  
     <name>ABC</name>
     <url>http://maven.apache.org</url>

       <properties>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
      <maven.compiler.source>1.6</maven.compiler.source>
      <maven.compiler.target>1.6</maven.compiler.target>
    </properties>

     <dependencies>  
     
     <dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>3.141.59</version>
    </dependency>
  
    
    <dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-core</artifactId>
    <version>4.0.1</version>
   </dependency>
 
     
     <dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>4.0.1</version>
    </dependency> 
 
      
     <dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-junit</artifactId>
    <version>4.0.1</version>   
    </dependency>
 
     
     <dependency>
    <groupId>info.cukes</groupId>
    <artifactId>gherkin</artifactId>
    <version>2.12.2</version>
    <scope>provided</scope>
    </dependency>
 
      
    <dependency>
    <groupId>net.masterthought</groupId>
    <artifactId>cucumber-reporting</artifactId>
    <version>4.10.0</version>
    </dependency>
 
      
     <dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>3.8.1</version>
    <scope>test</scope>
     </dependency>
 
     
    <dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-picocontainer</artifactId>
    <version>4.0.1</version>
    </dependency>

     <dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports-cucumber4-adapter</artifactId>
    <version>1.0.7</version>
</dependency>

    
     <dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>4.0.9</version>
    </dependency>  
     </dependencies>  
      <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.7</version>
            </plugin>
        </plugins>
    </build>
</project>

       My Test Runner file
	@RunWith(Cucumber.class)
	@CucumberOptions(
			features = "C:/Users/MangalaHegde/eclipse- 
            workspace/LandGRegression/src/main/java/Features", tags= {"@TC_01_Log_in_screen"}	 
             ,//"@Individual_Workflow_add_amendment"//the path of the feature files
			glue={"stepDefinations"}, //the path of the step definition files
			
			//plugin= {"pretty", "html:target/cucumber/cucumber.html"},
			plugin =       
    
                {"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:",
              "json:target/cucumber-  report.json"},
			monochrome = true, //display the console output in a proper readable format
			strict = false, //it will check if any step is not defined in step definition file
			dryRun = false //to check the mapping is proper between feature file and step def file
				
			)

                public class TestRunner {
		
		@AfterClass
		 public static void writeExtentReport() {
				}`

**Comment by HegdeMangala** [comment]
[POM.txt](https://github.com/extent-framework/extentreports-cucumber4-adapter/files/3730365/POM.txt)

**Comment by thomasdeurloo** [comment]
Hi! you need to start the report and specify the output file by setting the Initialization Properties.

Try adding this to the testrunner instead of the afterclass method.
```
@BeforeClass
public static void startExtentReport() {
	System.setProperty("extent.reporter.html.start", "true");
	System.setProperty("extent.reporter.html.out", "output/report.html");
	//if you have a custom config xml add next line and specify the path
	//System.setProperty("extent.reporter.email.config", "<path to xml here>");
}

```
I think that should work.

if you want to start the logger reporter (html logger) as well then add these also:
```
System.setProperty("extent.reporter.logger.start", "true");
System.setProperty("extent.reporter.logger.out", "output/logger");
```

See full docs [here](http://extentreports.com/docs/versions/4/java/extentservice.html), refered from [here](http://extentreports.com/docs/versions/4/java/cucumber4.html)

**Comment by anshooarora** [comment]
@thomasdeurloo thank you!
