### ISSUE TITLE
Extent-report folder is not generating

### ISSUE THREAD

**Issue by mounikaakuthota12** [extent-framework/extentreports-cucumber4-adapter#36]
Hi,
I am facing the same issue, it does not create extent report folder under test-output.Below is my extent dependency in pom.xml file

4.2.0 3.141.59 1.2.1 1.7.21 4.7.2 2.7.0 1.3.2 3.4 1.18.8 3.2.0 7.0.0 1.6 2.22.2 1.6.0 3.1.0 3.8.1 4.8.0 6.14.2 UTF-8 2.5 1.8 5.1.6 2.6.3

<build>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>${maven-compiler-plugin}</version>
			<configuration>
				<encoding>${utf-8}</encoding>
				<source>${java-version}</source>
				<target>${java-version}</target>
			</configuration>
		</plugin>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-surefire-plugin</artifactId>
			<version>${maven-surefire-plugin}</version>
			<executions>
				<execution>
					<id>test</id>
					<phase>test</phase>
					<goals>
						<goal>test</goal>
					</goals>
					<configuration>
						<threadCount>4</threadCount>
						<perCoreThreadCount>true</perCoreThreadCount>
						<forkCount>4</forkCount>
						<reuseForks>false</reuseForks>
						<argLine>-Duser.language=en</argLine>
						<argLine>-Xmx1024m</argLine>
						<argLine>-XX:MaxPermSize=256m</argLine>
						<argLine>-Dfile.encoding=UTF-8</argLine>
						<useFile>false</useFile>
						<includes>
							<include>${testToRun}</include>
						</includes>
						<testFailureIgnore>true</testFailureIgnore>
					</configuration>
				</execution>
			</executions>
		</plugin>
		<plugin>
			<groupId>org.codehaus.mojo</groupId>
			<artifactId>exec-maven-plugin</artifactId>
			<version>${mojo-exec-maven-plugin}</version>
			<executions>
				<execution>
					<phase>test</phase>
					<goals>
						<goal>java</goal>
					</goals>
				</execution>
			</executions>
			<configuration>
				<mainClass>com.cbs.test.ReportMerger</mainClass>
				<arguments>
					<argument>target/cucumber-report/</argument>
				</arguments>
			</configuration>
		</plugin>

		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-resources-plugin</artifactId>
			<version>${maven-resource-plugin}</version>
			<configuration>
				
				<encoding>${utf-8}</encoding>

				<resources>
					<resource>
						<directory>src/main/resources</directory>
						<filtering>true</filtering>
					</resource>
				</resources>

			</configuration>
		</plugin>

		<plugin>
			<groupId>net.masterthought</groupId>
			<artifactId>maven-cucumber-reporting</artifactId>
			<version>${maven-cucumber-reporting}</version>
			<executions>
				<execution>
					<id>execution</id>
					<phase>test</phase>
					<goals>
						<goal>generate</goal>
					</goals>
					<configuration>
						<projectName>cucumbertests</projectName>
						<outputDirectory>target/cucumber-report/cucumber-html-reports</outputDirectory>
						<inputDirectory>target/cucumber-report</inputDirectory>

						<jsonFiles>
							
							<param>**/*cucumber.json</param>
						</jsonFiles>

					</configuration>
				</execution>
			</executions>
		</plugin>

	</plugins>

	
	<resources>
		<resource>
			<directory>src/main/resources</directory>
			<filtering>true</filtering>
		</resource>
	</resources>
<dependencies>

<dependency>
		<groupId>com.aventstack</groupId>
		<artifactId>extentreports-cucumber4-adapter</artifactId>
		<version>1.0.7</version>
		<exclusions>
			<exclusion>
				<groupId>io.cucumber</groupId>
				<artifactId>cucumber-java</artifactId>

			</exclusion>
			<exclusion>
				<groupId>io.cucumber</groupId>
				<artifactId>cucumber-core</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
	<dependency>
		<groupId>io.cucumber</groupId>
		<artifactId>cucumber-java8</artifactId>
		<version>${cucumber.version}</version>
	</dependency>
	<dependency>
		<groupId>io.cucumber</groupId>
		<artifactId>cucumber-testng</artifactId>
		<version>${cucumber.version}</version>
		<scope>test</scope>
	</dependency>

And the runner class where I have the extent pluigin

package com.cbs.test;

import cucumber.api.CucumberOptions;
import cucumber.api.testng.AbstractTestNGCucumberTests;

//import cucumber.api.CucumberOptions;
//import cucumber.api.testng.AbstractTestNGCucumberTests;

@CucumberOptions(features = "target/test-classes", tags = { "@MobileSA" }, monochrome = true, plugin = { "pretty",
"html:target/cucumber-report/webapp", "json:target/cucumber-report/webapp/cucumber.json",
"rerun:target/cucumber-report/webapp/rerun.txt",
"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:" }, glue = {
"com.cbs.test.framework.hooks", "com.cbs.test.step_definitions.mobile" })
public class RunAndroidAppSuite extends AbstractTestNGCucumberTests {

public RunAndroidAppSuite() {
	DriverObject.android();
}
}

extent.properties:

extent.reporter.html.start=true
extent.reporter.logger.start=true
extent.reporter.spark.start=true

extent.reporter.html.config=src/test/resources/extent-config.xml
extent.reporter.logger.config=src/test/resources/extent-config.xml
extent.reporter.spark.config=src/test/resources/extent-config.xml

extent.reporter.html.out=test-output/HtmlReport/ExtentHtml.html
extent.reporter.logger.out=test-output/Logger
extent.reporter.spark.out=test-output/Spark

screenshot.dir=test-output/HtmlReport/

Could you please look into the issue?

--

**Comment by thomasdeurloo** [comment]
is it running your tests correctly? if yes, then maybe it is not loading the properties.
you can try to set the properties in the system properties instead of a properties file.
add somethings like this in your testrunner:

```
public class RunAndroidAppSuite extends AbstractTestNGCucumberTests {

@BeforeClass
public static void startExtentReport() {
	System.setProperty("extent.reporter.html.start", "true");
	System.setProperty("extent.reporter.html.out", "test-output/HtmlReport/ExtentHtml.html");
}

public RunAndroidAppSuite() {
DriverObject.android();
}
}

```

Does that make any difference?

**Comment by anshooarora** [comment]
I am marking this issue as invalid.  Please format your question properly so its easily read.  Feel free to open a new ticket if the issue still persists, thank you.
