### ISSUE TITLE
Unable to make step as fail when any if else condition fails

### ISSUE THREAD

**Issue by agileselenium** [extent-framework/extentreports-cucumber4-adapter#37]
build.gradle:
io.cucumber:cucumber-java:4.7.4
io.cucumber:cucumber-testng:4.7.4
com.aventstack.extentreports-cucumber4-adapter:1.0.8

Runner class:

plugin = {"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:", "json:target/cucumber-report.json"}
public class myRunner extends AbstractTestNGCucumberTests {
    @Override
    @DataProvider(parallel=true)
    public Object[][] scenarios() {
        return super.scenarios();
    }
}

page file:
if(driver.findElement(By.xpath("//input[@name='the_name']")).isEnabled()){
  //set step as pass in extent report
}else{
  //set step to fail in extent reprot
}

**Comment by anshooarora** [comment]
You can throw an exception and the appropriate hook will be called and the exception will be registered.  Pseudo code:

```
else {
   throw new ElementNotEnabledException("");
}
```
