### ISSUE TITLE
In generated report Screen shot URL is absolute path instead of relative path

### ISSUE THREAD

**Issue by samaran43** [extent-framework/extentreports-cucumber4-adapter#38]
Hi, 
I am using "extentreports-cucumber4-adapter" in my project. I am facing following issue. Can any resolve this? 

1. I have configured the screen shot directory as "screenshot.dir=test-output/screenshots" in properties file it working for me. but the thing is, In generated report screen shot path formed by absolute path instead of absolute path.  So when i send my report to someone then screen shot is displaying in the report since it's absolute path. 

can anyone solve this? Or any alternate way to resolve this issue?

**Comment by anshooarora** [comment]
This behavior is due to the following:  https://github.com/extent-framework/extentreports-cucumber4-adapter/blob/master/src/main/java/com/aventstack/extentreports/cucumber/adapter/ExtentCucumberAdapter.java#L213

This must be changed to the as-is path provided by `screenshot.dir`.

**Comment by anshooarora** [comment]
@samaran43 Please view #20.  The latest snapshot provides the ability to specify the relative path from the report to display screenshots.

**Comment by samaran43** [comment]
> @samaran43 Please view #20. The latest snapshot provides the ability to specify the relative path from the report to display screenshots.

Hi @anshooarora , thank you valuable response. When can i get the final version of 1.0.11  in MVN repository?

**Comment by anshooarora** [comment]
@samaran43 This was a SNAPSHOT version until today,  I have just released it and may take a few hours to reflect [here](https://mvnrepository.com/artifact/com.aventstack/extentreports-cucumber4-adapter/1.0.11).

**Comment by anshooarora** [comment]
@samaran43 are you still experiencing this issue, or can it be closed?

**Comment by samaran43** [comment]
Hi @anshooarora , Issue resoved we can close this
