### ISSUE TITLE
License in pom file is not matching license in github - v1.0.10

### ISSUE THREAD

**Issue by mkvetko** [extent-framework/extentreports-cucumber4-adapter#39]
Recently I was dealing with an issue with upgrading the adapter version to the latest 1.0.10. We use in my company private nexus with proxy to maven central and before we add something to our private nexus from maven central there are some automatic checks applied. A license on the artifact is one of them. 1.0.10 has changed license in pom file from MIT to The Apache Software License, Version 2.0 which is not passing our checks hence we can't update to the latest version. Previous versions were using MIT license and github is still mentioning MIT license so before I try to convince our IT security department to change rules which may have a huge impact on us as we are big company and will be likely rejected I would like to know if this was an intentional change or just someone's mistake.

Can you please confirm that since now on you will release cucumber4 adapter under The Apache Software License, Version 2.0?

**Comment by anshooarora** [comment]
@mkvetko All products under the framework will be licensed under Apache2. All repos, artifact managers will be updated to reflect this change very soon.

**Comment by mkvetko** [comment]
Thanks a lot for the reply
