### ISSUE TITLE
ExtentSparkReport html file

### ISSUE THREAD

**Issue by LearningPur** [extent-framework/extentreports-cucumber4-adapter#40]
Hi @anshooarora Is there a workaround sending only index.html file to other party (Stackholder) to review the list of automation test cases can have an access of "dashboard as well tag" on click of it ? 

**ExtentHtmlReporter used to provide this feature just by sending index.html file other can also view the dashboard and tag or any object that are visible in index.html.**

**ExtentSparkReporter forcefully required to send dashboard.html and tag.html files along with index.html.**

Please find attached below 2 zip files

1) Just index html file : This has only index.html file when you open it and navigate to dashboard or tag it throws "Your file was not found" error on browser

[Just index html file.zip](https://github.com/extent-framework/extentreports-cucumber4-adapter/files/4176372/Just.index.html.file.zip)

2) index dashboard and tag html files : This has index, dashboard and tag html files. When you open index.html in any browser and navigate to dashboard or tag it does allow to view it. 

[index dashboard and tag html files.zip](https://github.com/extent-framework/extentreports-cucumber4-adapter/files/4176373/index.dashboard.and.tag.html.files.zip)

Thanks
Victor

**Comment by LearningPur** [comment]
@anshooarora , If you have few min can you please reply on my question above.

Thanks
Victor

**Comment by anshooarora** [comment]
Starting `extentreports:4.1.0`, Spark creates a single file just like HtmlReporter.  Can you add latest as a dependency and check?

**Comment by anshooarora** [comment]
Also - refer [changelog](https://github.com/extent-framework/extentreports-java/blob/master/CHANGELOG.md).

**Comment by LearningPur** [comment]
Thanks @anshooarora will update the dependency and check.

**Comment by LearningPur** [comment]
It worked @anshooarora  thanks
