### ISSUE TITLE
Questions about deprecated ExtentHtmlReporter

### ISSUE THREAD

**Issue by lucascologni** [extent-framework/extentreports-cucumber4-adapter#42]
Hello! How are you?

I'm using ExtentReports, I liked so much the look of the report itself, but I have a couple of questions, can you help me?

1 - The "ExtentHtmlReporter" is deprecated, was it replaced to another one or other class? If yes, what similar report can I use that has the same rich layout?

2 - I'm reading the "extent-config.xml" layout, so I would like to customize the configuration of the report in runtime on my "runner" class, how can I do this?
![image](https://user-images.githubusercontent.com/12294328/75451941-2159a400-5950-11ea-8c64-7bf0080e7908.png)

I used to customize the configs in my reports using something like method .config() on "ExtentHtmlReporter":
![image](https://user-images.githubusercontent.com/12294328/75452642-6cc08200-5951-11ea-818c-170465f1727c.png)

![image](https://user-images.githubusercontent.com/12294328/75452210-a3e26380-5950-11ea-8e3b-10a1bc4a14b8.png)

I there other similar report that is not deprecated that I can use to replace? Wich has the same way to customize the configs?

Thank you very much, I would be glad if you halp me out!

**Comment by PeterMarton** [comment]
Hi, 
may it is late  abit and probably you found the answer, but if not. 

https://github.com/extent-framework/extentreports-java/blob/master/CHANGELOG.md

ExtentSparkReporter.java is your friend from now on.
