### ISSUE TITLE
Incorrect status shown in Extent HTML report

### ISSUE THREAD

**Issue by Lakssh** [extent-framework/extentreports-cucumber4-adapter#44]
Hi,

I am using extent adapter 1.0.10 and facing a weird issue of incorrect status being displayed in the HTML report. 
Actually Executed 4 tests and 2 are failed. However in the extent report, it shows as below
![image](https://user-images.githubusercontent.com/33589766/76316323-4f38d400-62d2-11ea-9229-e1e0dd10fe2c.png)

**Extent report dependency**
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports-cucumber4-adapter</artifactId>
			<version>1.0.10</version>
		</dependency>

**cucumber and testng versions**
		<io.cucumber>4.8.1</io.cucumber>
		<org.testng.testng>7.1.0</org.testng.testng>

**Extent Properties**

extent.reporter.avent.start=false
extent.reporter.bdd.start=false
extent.reporter.cards.start=false
extent.reporter.email.start=false
extent.reporter.html.start=true
extent.reporter.klov.start=false
extent.reporter.logger.start=false
extent.reporter.spark.start=false
extent.reporter.tabular.start=false

extent.reporter.avent.config=
extent.reporter.bdd.config=
extent.reporter.cards.config=
extent.reporter.email.config=
extent.reporter.html.config=
extent.reporter.klov.config=src/test/resources/com/aventstack/adapter/klov.properties
extent.reporter.logger.config=
extent.reporter.spark.config=
extent.reporter.tabular.config=

extent.reporter.avent.out=test-output/AventReport/
extent.reporter.bdd.out=test-output/BddReport/
extent.reporter.cards.out=test-output/CardsReport/
extent.reporter.email.out=test-output/EmailReport/ExtentEmail.html
extent.reporter.html.out=test-output/HtmlReport/ExtentHtml.html
extent.reporter.logger.out=test-output/LoggerReport/
extent.reporter.spark.out=test-output/SparkReport/
extent.reporter.tabular.out=test-output/TabularReport/

screenshot.dir=test-output/
screenshot.rel.path=../

**Comment by zuzeac** [comment]
A similar problem I encounter were the skipped scenarios are not recorded.
Only fails and pass.
One device just died and the rest of the test were skipped but not recorded in extent or spark report.
Any idea?

**Comment by anshooarora** [comment]
Please check with version 1.0.11 using SparkReporter.  HtmlReporter has been deprecated.

**Comment by anshooarora** [comment]
This has been fixed in #50.  https://github.com/extent-framework/extentreports-cucumber4-adapter/commit/00526ec129986f839cc982b8bd9d3e6c82e7ae7d
