### ISSUE TITLE
Log info in the steps

### ISSUE THREAD

**Issue by iyustlop** [extent-framework/extentreports-cucumber4-adapter#49]
Hi, 

In the past I use Extent Report widely using Listener. Then I have a class that contains the loging mechanism.

With the plugin I want to log the same information but I don't find an example to follow. I want to include the response of a RestAssured Request in the report but I don't find the way to do it.

I have implemented in the Runner Class the plugin configuration. 

Could you share a example??

Thank you very much indeed.

**Comment by anshooarora** [comment]
@iyustlop You can do so using:

```
ExtentCucumberAdapter.addTestStepLog(message);
```
