### ISSUE TITLE
Not able to jump directly to scenario

### ISSUE THREAD

**Issue by tgoswami013** [extent-framework/extentreports-cucumber4-adapter#59]
Once I click on failed TestName inside bug/tag section, it redirect me to top of feature which is failed. I want to reach to particular failed scenario directly so that I can see at which step it failed instead of scrolling to the scenario.

Also, this report is at feature level and scenarios grouped together inside it. Can we create report scenario-wise.

**Comment by anshooarora** [comment]
This has to happen via ExtentReports, I have raised a ticket referencing this.  You can track it using:

https://github.com/extent-framework/extentreports-java/issues/191

**Comment by anshooarora** [comment]
@tgoswami013 This enhancement is now included, you can test it here:

http://extentreports.com/samples/attrNavToTest/nodes.html

**Comment by tgoswami013** [comment]
Thanks a lot!
