### ISSUE TITLE
Adding log into every steps in Html report

### ISSUE THREAD

**Issue by mohamadsyauqi** [extent-framework/extentreports-cucumber4-adapter#7]
I cannot find any documentation to add log/text into the step.  
I tried using scenario.write but it only works for the original cucumber html report not for the extent report.  
I assumed extent report can do this because it can add screenshot after every step.  
  
Thanks in advance.

**Comment by anshooarora** [comment]
@mohamadsyauqi This would be done via the [writeEvent](https://github.com/extent-framework/extentreports-cucumber4-adapter/blob/master/src/main/java/com/aventstack/extentreports/cucumber/adapter/ExtentCucumberAdapter.java#L217).  

Please feel free to send a PR.

**Comment by mohamadsyauqi** [comment]
I'm not really a good programmer, but I tried to add this into the code :
```
String text = event.text;
    	if(text != null){
    		for(String splitText : text.split("\n")){
    			stepTestThreadLocal.get().info(splitText);
    		}
    	}
```
It works just fine. I don't know what else to check/add. Like I said I'm not really a good programmer, but if this is okay and you want me to send a PR, let me know.

**Comment by anshooarora** [comment]
Thank you, I am checking now.

**Comment by anshooarora** [comment]
This looks good.  Although, I don't think you need to split using a `\n` because it will create multiple events for each step.  I would just log as a single step:

```
String text = event.text;
if (text != null && !text.isEmpty()) {
    stepTestThreadLocal.get().info(text.replace("\n", "<br/>"));
}
```

**Comment by mohamadsyauqi** [comment]
Btw, is there a way to make the info log show in the report like the fail log? Meaning it can collapse and expand.
   
![fail log](https://user-images.githubusercontent.com/46016468/50627576-091a0f00-0f6f-11e9-8880-a8f3e87c01f7.PNG)
  
I think example above shows both how the info log and fail log behaves. I want to make the info log shows like the fail log.   
The reason for this is I want to put all the data as a debug log in the info log where I put all the REST API request and response.   
Sometimes the json files are quite large so I have to scroll a lot to go to the next step and the report will be so clutter that it will be hard to find any specific step.   
Is there a way to do this?   
Below is the current way I use to handle my log.
```
public static void info(String text) {
	scenario.write("[INFO] " + text + "\n");
}

public static void debug(String text) {
	if(ConfigFileReader.get("debug.level").equalsIgnoreCase("on"))
		scenario.write("[DEBUG] " + text + "\n");
}
```
Thanks in advance.

**Comment by anshooarora** [comment]
At the moment, no, not by default.  But this can be achieved using custom JavaScript.  I would not like to change existing features for this reporter as it may confuse users who are used to using this reporter in the current way.

This can be achieved using the new reporter for version 4 for which I have created a poll [here](https://github.com/extent-framework/extentreports-java/issues/19).  However, I do feel there is lack of support for this so far..

**Comment by mohamadsyauqi** [comment]
> Btw, is there a way to make the info log show in the report like the fail log? Meaning it can collapse and expand.
> 
> ![fail log](https://user-images.githubusercontent.com/46016468/50627576-091a0f00-0f6f-11e9-8880-a8f3e87c01f7.PNG)
> 
> I think example above shows both how the info log and fail log behaves. I want to make the info log shows like the fail log.
> ...
   
I figured out the simplest way to tackle this problem. I created a method to handle all the log and put it into a textarea. Below is the method I did 
```
public static void createLog(){
	if(!logText.isEmpty())
		scenario.write("<textarea disabled>" + logText + "</textarea>");
}
```
For this to work correctly the handleWrite method also needed to change to not replace the \n with < br/ >
```
private void handleWrite(WriteEvent event) {
	String text = event.text;
	if (text != null && !text.isEmpty()) {
	    stepTestThreadLocal.get().info(text);
	}
}
```
What do you think of not replacing \n for the handleWrite @anshooarora ? I think the pros is user can have more customizability and the cons is the user have to put < br/ > themselves if they want.
